### ISSUE TITLE
LVS-Simphys  -no damage to vehicles

### ISSUE THREAD

**Issue by Exidnost** [Blu-x92/lvs_cars#10]
Why do collisions not cause damage to vehicles on LVS and no longer occur in Simphys? I tested these addons separately and without unnecessary addons, but still no damage is caused to the car in collisions.

**Comment by Yopizza** [comment]
This is the same issue i have, the cars will take damage from guns and stuff but not from collisions

**Comment by Diaz0410** [comment]
Especially nextbots with overlay or Drgbase stuff. except with damages that I'm immune to nextbot kill until car exploded.

**Comment by Blu-x92** [comment]
intentional
