### ISSUE TITLE
CTD after firing weapons on some LVS-based vehicles

### ISSUE THREAD

**Issue by KekkyShmekky** [Blu-x92/lvs_cars#2]
Specifically the T-34 from this addon: https://steamcommunity.com/sharedfiles/filedetails/?id=3027532062&searchtext=lvs+cars

[769708DF-5E04-419F-B838-982A5F77FFE0.txt](https://github.com/Blu-x92/lvs_cars/files/12480306/769708DF-5E04-419F-B838-982A5F77FFE0.txt)

**Comment by Blu-x92** [comment]
The T-34 addon isnt working correctly in many places. We have asked them to hide it on workshop until they finish it
