### ISSUE TITLE
Wheel System Bug

### ISSUE THREAD

**Issue by eonapsy** [Blu-x92/lvs_cars#4]
Error: addons/lvs_cars/lua/entities/lvs_base_wheeldrive/sv_wheelsystem.lua:80: attempt to call method 'SetWheelType' (a nil value)
[LVS-Cars] Wheels require higher MaxAngularVelocity to perform correctly! Increasing! 7272.7280273438 =>24000

Produce by spawning any LVS Car

**Comment by Blu-x92** [comment]
update addon and restart your game.
