### ISSUE TITLE
Complaint about mouse steering

### ISSUE THREAD

**Issue by Eye29** [Blu-x92/lvs_cars#7]
I host a Gmod server for ten of my friends and all of us play on it on a regular basis and the only complaint literally every single person on the server had was the fact that you can't enable and disable mouse steering independently from the cars and planes. I just wanted to post this to let you know what my people think so we can hopefully get some of these features in the future however I don't know if this is an LVS base problem or an LVS cars problem since I have zero experience with modding so apologies if I sent this to the wrong GitHub page.

**Comment by Blu-x92** [comment]
only solution i can give you is a bind:

bind X lvs_mouseaim_toggle

then press X to switch

**Comment by Eye29** [comment]
Thanks!
