### ISSUE TITLE
Cars will not drive at all.

### ISSUE THREAD

**Issue by WolfKann** [Blu-x92/lvs_cars#8]
Basically what the title says, I've tried custom addon packs and also base cars but using any WASD keys does not allow the vehicles to move.

Console just keeps spamming

[[LVS] - Cars [Fake Physics]] lua/entities/gmod_sent_vehicle_fphysics_base/init.lua:633: attempt to call method 'GetRPM' (a nil value)
1. SimulateVehicle - lua/entities/gmod_sent_vehicle_fphysics_base/init.lua:633
2. unknown - lua/entities/gmod_sent_vehicle_fphysics_base/init.lua:156

**Comment by Blu-x92** [comment]
addon conflict, you have outdated code in your game for some reason. Most likely someone smuggled a custom wheel entity to overwrite the original one. Nothing i can do from my end.
